pipeline:
    name: CICD-Sample
    identifier: CICDSample
    allowStageExecutions: false
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-march
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test_build_run
                                identifier: test_build_run
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    command: echo "<+pipeline.variables.MAGIC.toLowerCase()>"
        - stage:
              name: deploy
              identifier: deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: lscjf
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: rajathak8
                              namespace: rajatha-delegate-march
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: stg2
                                identifier: stg2
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo "<+pipeline.variables.MAGIC.toLowerCase()>"
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    variables:
        - name: MAGIC
          type: String
          value: RAJATHA
