pipeline:
    name: DockerPushSample
    identifier: DockerPushSample
    allowStageExecutions: false
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-april
                          automountServiceAccountToken: true
                          containerSecurityContext:
                              runAsUser: "1000"
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run
                                identifier: run
                                spec:
                                    connectorRef: dockerrajatha
                                    image: golang:1.15
                                    shell: Sh
                                    command: |-
                                        #!/bin/sh
                                        echo <+codebase.targetBranch>
                                        echo <+codebase.sourceBranch>
                                        export LATEST_BRANCH="master"
                                        if [ <+codebase.targetBranch> == "master" ]
                                        then
                                           export LATEST_BRANCH="heelotag, master"
                                        else
                                           export LATEST_BRANCH="hellotag, non-master"
                                        fi

                                        go get gotest.tools/gotestsum
                                        gotestsum --format=standard-verbose --junitfile unit-tests.xml || true
                                        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                                    outputVariables:
                                        - name: LATEST_BRANCH
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: build and push
                                identifier: build_and_push
                                spec:
                                    connectorRef: dockerrajatha
                                    repo: rajatharanganath/ciquickstart
                                    tags:
                                        - <+pipeline.sequenceId>
                                        - <+execution.steps.run.output.outputVariables.LATEST_BRANCH>
                                        - pr-<+codebase.prNumber>
        - stage:
              name: stg2
              identifier: stg2
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: lscjf
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                              manifests: []
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: rajathak8
                              namespace: rajatha-delegate-april
                              releaseName: release-<+codebase.prNumber>-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: stp1
                                identifier: stp1
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                echo <+codebase.prNumber>
                                                echo test
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - Unknown
                        action:
                            type: StageRollback
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: ManualIntervention
                            spec:
                                timeout: 10m
                                onTimeout:
                                    action:
                                        type: Abort
