pipeline:
    name: DockerPushSample
    identifier: DockerPushSample
    allowStageExecutions: false
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-march
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: run
                                identifier: run
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    shell: Sh
                                    command: |-
                                        #!/bin/sh
                                        echo <+codebase.targetBranch>
                                        echo <+codebase.sourceBranch>
                                        export LATEST_BRANCH="master"
                                        if [ <+codebase.targetBranch> == "master" ]
                                        then
                                           export LATEST_BRANCH="heelotag, master"
                                        else
                                           export LATEST_BRANCH="hellotag, non-master"
                                        fi
                                    outputVariables:
                                        - name: LATEST_BRANCH
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: build and push
                                identifier: build_and_push
                                spec:
                                    connectorRef: dockerrajatha
                                    repo: rajatharanganath/ciquickstart
                                    tags:
                                        - <+pipeline.sequenceId>
                                        - <+execution.steps.run.output.outputVariables.LATEST_BRANCH>
