pipeline:
  name: GitCloneIssue
  identifier: GitCloneIssue
  projectIdentifier: RajathaTest2
  orgIdentifier: default
  stages:
    - stage:
        name: Stage1
        identifier: Stage1
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: rajathak8
              namespace: rajatha-delegate-april
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: git cmd
                  identifier: git_cmd
                  spec:
                    connectorRef: dockerrajatha
                    image: <+input>
                    shell: Sh
                    command: |-
                      git config --global --add safe.directory /harness
                      git status
                      git branch
                      ls
              - step:
                  type: Background
                  name: background step
                  identifier: background_step
                  spec:
                    connectorRef: dockerrajatha
                    image: mysql:5
                    shell: Sh
              - step:
                  type: Run
                  name: sleep
                  identifier: sleep
                  spec:
                    connectorRef: dockerrajatha
                    image: alpine
                    shell: Sh
                    command: sleep 1000
    - stage:
        name: stg2
        identifier: stg2
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            useFromStage: Stage1
          execution:
            steps:
              - step:
                  type: Run
                  name: sdfsdf
                  identifier: sdfsdf
                  spec:
                    connectorRef: dockerrajatha
                    image: alpine
                    shell: Sh
                    command: echo test
        when:
          pipelineStatus: Failure
  properties:
    ci:
      codebase:
        connectorRef: githubrajatha
        build: <+input>
