pipeline:
    name: rajathaexp
    identifier: rajathaexp
    allowStageExecutions: false
    projectIdentifier: gitexptest
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubexp
                build: <+input>
    stages:
        - stage:
              name: stage1
              identifier: stage1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8s
                          namespace: harness-delegate-ng
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: account.harnessImage
                                    image: alpine
                                    command: echo rajatha-exp-test
