pipeline:
  name: ResourceUtilization
  identifier: ResourceUtilization
  projectIdentifier: RajathaTest2
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubrajatha
        build: <+input>
  stages:
    - stage:
        name: Stg1
        identifier: Stg1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: rajathak8
              namespace: rajatha-delegate-april
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: lint
                      identifier: lint
                      spec:
                        connectorRef: <+input>
                        image: <+input>
                        shell: Sh
                        command: |-
                          echo test
                          sleep 100000
                  - step:
                      type: Run
                      name: test
                      identifier: test
                      spec:
                        connectorRef: <+input>
                        image: <+input>
                        shell: Sh
                        command: |-
                          echo test
                          sleep 100000
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsSuccess
