pipeline:
    name: StepGroupSample
    identifier: StepGroupSample
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: stg1
              identifier: stg1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: lscjf
                      serviceDefinition:
                          spec:
                              variables: []
                          type: Kubernetes
                  infrastructure:
                      environmentRef: dev
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: rajathak8
                              namespace: rajatha-delegate-april
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - stepGroup:
                                name: group1
                                identifier: group1
                                steps:
                                    - parallel:
                                          - step:
                                                type: ShellScript
                                                name: xcdsfdf
                                                identifier: xcdsfdf
                                                spec:
                                                    shell: Bash
                                                    onDelegate: true
                                                    source:
                                                        type: Inline
                                                        spec:
                                                            script: echo test
                                                    environmentVariables: []
                                                    outputVariables: []
                                                    executionTarget: {}
                                                timeout: 10m
                                                failureStrategies: []
                                          - step:
                                                type: ShellScript
                                                name: asdasd
                                                identifier: asdasd
                                                spec:
                                                    shell: Bash
                                                    onDelegate: true
                                                    source:
                                                        type: Inline
                                                        spec:
                                                            script: echo test2
                                                    environmentVariables: []
                                                    outputVariables: []
                                                    executionTarget: {}
                                                timeout: 10m
                                    - step:
                                          type: K8sScale
                                          name: zzxfxf
                                          identifier: zzxfxf
                                          spec:
                                              workload: "5"
                                              skipSteadyStateCheck: false
                                              instanceSelection:
                                                  type: Count
                                                  spec:
                                                      count: 1
                                          timeout: 10m
                                failureStrategies: []
                                spec: {}
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
