pipeline:
    name: TractableRepro
    identifier: TractableRepro
    allowStageExecutions: false
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: Stg1
              identifier: Stg1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-march
                  execution:
                      steps:
                          - step:
                                name: stgSample
                                identifier: stgSample
                                template:
                                    templateRef: TractableStepTemplate
                                    versionLabel: "1"
                                    templateInputs:
                                        type: Run
                                        spec:
                                            envVariables:
                                                ENV: <+input>
                                                SPEC: <+input>
                                                TAGS: <+input>
                                                SLACK_CHANNEL: <+input>
