pipeline:
  name: Tratable replica
  identifier: Tratable_replica
  projectIdentifier: RajathaTest2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test Image
        identifier: Test_Image
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            useFromStage: Build
          execution:
            steps:
              - step:
                  type: Run
                  name: List program versions
                  identifier: List_program_versions
                  spec:
                    connectorRef: account.Tractable_Docker_Hub
                    image: <+pipeline.stages.Build.spec.execution.steps.Generate_Docker_Tag.output.outputVariables.DOCKER_IMAGE_WITH_TAG>
                    shell: Bash
                    command: |
                      whoami
                      printenv

                      ls -al /root/.asdf

                      git --version
                      aws --version
                      asdf --version
                      python --version
                    imagePullPolicy: Always
                    runAsUser: "0"
