pipeline:
    name: TemplateTest
    identifier: TemplateTest
    allowStageExecutions: true
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: stage1
              identifier: stage1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-april
                          automountServiceAccountToken: true
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    shell: Sh
                                    command: |-
                                        echo "<+<+pipeline.variables.MAGIC>.toLowerCase()>"
                                        echo pr-<+codebase.prNumber>
              when:
                  pipelineStatus: Success
              failureStrategies: []
        - stage:
              name: stg2
              identifier: stg2
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      useFromStage: stage1
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: sdwafsdf
                                identifier: sdwafsdf
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    shell: Sh
                                    command: |-
                                        echo test
                                        echo test2
    variables:
        - name: MAGIC
          type: String
          value: <+input>
