pipeline:
    stages:
        - stage:
              when:
                  pipelineStatus: Success
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          os: Linux
                          namespace: rajatha-delegate-april
                          containerSecurityContext:
                              runAsUser: "10000"
                          connectorRef: rajathak8
                          automountServiceAccountToken: false
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    shell: Sh
                                    image: alpine/git:latest
                                    connectorRef: dockerrajatha
                                    command: |
                                        ls -ltra /harness
                                        git --version 
                                        ##git config --global --add safe.directory /harness
                                        git tag <+pipeline.executionId>
                                name: test
                                identifier: test
                  cloneCodebase: true
              name: stage1
              identifier: stage1
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    name: TemplateTest
    identifier: TemplateTest
    allowStageExecutions: true
