pipeline:
    variables:
        - value: <+input>.allowedValues(a,b,c)
          type: String
          name: MAGIC
    stages:
        - stage:
              when:
                  pipelineStatus: Success
              variables:
                  - value: 2Gi
                    type: String
                    name: memory
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          os: Linux
                          namespace: rajatha-delegate-april
                          containerSecurityContext:
                              runAsUser: "10000"
                          connectorRef: rajathak8
                          automountServiceAccountToken: false
                          annotations:
                              ASSUME_ROLE_ARN: <+input>
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    shell: Sh
                                    resources:
                                        limits:
                                            cpu: <+stage.variables.memory>
                                    image: alpine/git:latest
                                    connectorRef: dockerrajatha
                                    command: |-
                                        git --version 
                                        git tag <+pipeline.executionId>
                                name: test
                                identifier: test
                  cloneCodebase: true
              name: stage1
              identifier: stage1
        - stage:
              type: CI
              spec:
                  infrastructure:
                      useFromStage: stage1
                  execution:
                      steps:
                          - step:
                                type: Run
                                spec:
                                    shell: Sh
                                    image: alpine
                                    connectorRef: dockerrajatha
                                    command: |-
                                        echo test
                                        echo test3
                                name: sdwafsdf
                                identifier: sdwafsdf
                  cloneCodebase: true
              name: stg2
              identifier: stg2
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    name: TemplateTest
    identifier: TemplateTest
    allowStageExecutions: true
