pipeline:
    name: TemplateTest
    identifier: TemplateTest
    allowStageExecutions: true
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: stage1
              identifier: stage1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: k8s
                          namespace: rajatha-delegate-april
                          annotations:
                              ASSUME_ROLE_ARN: <+input>
                          automountServiceAccountToken: false
                          nodeSelector: {}
                          containerSecurityContext:
                              runAsUser: "10000"
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    shell: Sh
                                    command: |-
                                        echo "<+<+pipeline.variables.MAGIC>.toLowerCase()>"
                                        echo pr-<+codebase.prNumber>
                                    resources:
                                        limits:
                                            cpu: <+stage.variables.memory>
              when:
                  pipelineStatus: Success
              failureStrategies: []
              variables:
                  - name: memory
                    type: String
                    value: 2Gi
        - stage:
              name: stg2
              identifier: stg2
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      useFromStage: stage1
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: sdwafsdf
                                identifier: sdwafsdf
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    shell: Sh
                                    command: |-
                                        echo test
                                        echo test3
    variables:
        - name: MAGIC
          type: String
          value: <+input>.allowedValues(100gi,200gb,300gi)
