pipeline:
    name: TemplateTest
    identifier: TemplateTest
    allowStageExecutions: false
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: stage1
              identifier: stage1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-march
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test
                                identifier: test
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    command: |-
                                        echo test
                                        export utdone="done"
                                        sleep 120
                          - step:
                                type: Run
                                name: test2
                                identifier: test2
                                spec:
                                    connectorRef: dockerrajatha
                                    image: alpine
                                    command: |
                                        echo <+pipeline.stages.stage1.spec.execution.steps.test.output.outputVariables>
