pipeline:
    name: TemplateTest
    identifier: TemplateTest
    allowStageExecutions: false
    projectIdentifier: RajathaTest2
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubrajatha
                build: <+input>
    stages:
        - stage:
              name: stage1
              identifier: stage1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: rajathak8
                          namespace: rajatha-delegate-march
                  execution:
                      steps:
                          - parallel:
                                - step:
                                      type: Run
                                      name: test
                                      identifier: test
                                      spec:
                                          connectorRef: dockerrajatha
                                          image: alpine
                                          command: |-
                                              echo test
                                              sleep 1000
                                              export utdone="done"
                                - step:
                                      type: Run
                                      name: test2
                                      identifier: test2
                                      spec:
                                          connectorRef: dockerrajatha
                                          image: alpine
                                          command: echo <+pipeline.stages.CI_Build_Process.spec.execution.steps.test.output.outputVariables.utdone>
